name: jiffy_klc
description: Jiffy_klc is a Jiffy extension package for lunar-solar date conversion.
version: 1.0.0
repository: https://github.com/JosephNK/jiffy_klc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jiffy: ^6.3.1
  klc: ^0.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
